### ISSUE TITLE
Error when starting Android app

### ISSUE THREAD

**Issue by Wallace121980** [kraffslol/react-native-braintree-xplat#12] opened 2016-09-29 12:16 UTC
I've got this error when I want to start the Android app. In iOS it works fine.

/Users/williamschrauwen/ReactNative/BraintreeSample/node_modules/react-native-braintree-xplat/android/src/main/java/com/pw/droplet/braintree/Braintree.java:22: error: Braintree is not abstract and does not override abstract method onActivityResult(Activity,int,int,Intent) in ActivityEventListener
public class Braintree extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
/Users/williamschrauwen/ReactNative/BraintreeSample/node_modules/react-native-braintree-xplat/android/src/main/java/com/pw/droplet/braintree/Braintree.java:108: error: method does not override or implement a method from a supertype
  @Override
  ^
2 errors
:react-native-braintree-xplat:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-braintree-xplat:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.834 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by kraffslol** [comment] 2016-09-29 12:29
Which version of RN are you using?

**Comment by Wallace121980** [comment] 2016-09-29 12:39
I've made an example app to test, so the newest version 0.34.1.

**Comment by cheqitout-dev** [comment] 2016-10-06 21:18
I'm getting the same error, using react-native 0.34

**Comment by the-simian** [comment] 2016-10-07 00:30
ok it looks like there is a fix for this on PR #16 ! if @kraffslol will go ahead and publish the latest to npm and increase the version - we can have the fix.

in the meantime: 
`"react-native-braintree-xplat": "https://github.com/kraffslol/react-native-braintree-xplat/tarball/master",`

in your package.json will get past the error.

**Comment by kraffslol** [comment] 2016-10-11 08:57
Should now be sorted out in the latest version.

**Closed by kraffslol** 2016-10-11 08:57 UTC

**Comment by the-simian** [comment] 2016-10-12 03:02
yep, I can confirm this is working just fine on the npm version! Thanks @kraffslol
